### ISSUE TITLE
The Cupids review

### ISSUE THREAD

**Issue by Blaise-Shyaka** [aracelicaes/library_js#1]
Well done on this project. Please kindly consider working on the following:
- [x] Add form validation to prevent the addition of an empty book
- [x] Reset the book container before displaying books
- [x] Remove commented code

**Comment by Miguelus373** [comment]
You're going pretty well! Just a few things:

- [x] Update the status button text and the localStorage synchronously
- [x] Use the index of the library array as the ID for the books

**Comment by aracelicaes** [comment]
All Issues Resolved.
